eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/auth/**
        - id: syllabus
          uri: http://localhost:8761
          predicates:
            - Path=/api/v1/auth/**
