eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/auth/**
        - id: syllabus-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**
        - id: training-program-service
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/auth/**
        - id: training-class-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/auth/**
