eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8095
spring:
  application:
    name: trainingprogram
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-sql:5432/trainingprogram
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    customer-url: http://localhost:8222/api/v1/auth
    syllabus-url: http://localhost:8222/api/v1/auth
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true