eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8095
spring:
  application:
    name: trainingprogram
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trainingprogram
    username: root
    password: Clp12345
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
application:
  config:
    customer-url: http://localhost:8222/api/v1/auth
    syllabus-url: http://localhost:8222/api/v1/auth